### ISSUE TITLE
[Crash Server Start 1.16.4]

### ISSUE THREAD

**Issue by SugarDaddii** [Azmalent/terra-incognita#20]
I dont know but i cant get any version after 1.1 to work for my server!

https://pastebin.com/Amge1kZS

**Comment by Azmalent** [comment]
This issue was already fixed, you should update to the latest version.

**Comment by Azmalent** [comment]
Sorry about that. This is weird, I was sure I fixed this in the 1.5.2 hotfix.
Try the 1.5.3.1 version, it should fix the issue.

**Comment by SugarDaddii** [comment]
Why Sometimes mods are working Clientside but not serverside? (Just for my understanding)

**Comment by Azmalent** [comment]
I assume you meant in singleplayer?
That's because some classes (like Screen which is used to define GUIs) only exist on the client side. If they are referred to in the code, JVM tries to load them, and this causes a crash on the server. Since in singleplayer your PC is a client and a server at the same time, the game has access to all the classes, and it works just fine despite crashing in multiplayer.
