### ISSUE TITLE
Inconsistent Decoration with modded Biomes.

### ISSUE THREAD

**Issue by SirChamomile** [Azmalent/terra-incognita#25]
I'm having mixed results with Terra Incognita decorating biomes. The main mods I'm using that add biomes are Environmental, Autumnity, Abundance, and Bayou Blues. 

It will decorate some biomes like the Marsh from environmental or the Lavender Fields from Abundance, but won't decorate certain biomes like the Bayou, any of the Autumnity biomes, or the Blossom biomes from Environmental. Any thoughts about what's going on? I'm not sure the issue is on your end, but I'm not having issues from More Flower Bushes for example.

**Comment by Azmalent** [comment]
It's probably because I'm using categories to determine what features to add to a biome, and some biomes might have a different category than one would expect. I.e. Rainforest from Atmoshperic is categorized as a forest and not a jungle, but I handle hot forests as jungles so it works in that case.

As far as Autumnity goes, their biomes are forests, and there aren't any forest flowers in the latest release (they will be added in the next version). Pumpkin fields should work fine though.

**Comment by Azmalent** [comment]
Update: I checked Environmental biomes and the Bayou, they are working just fine for me. 
Are you sure you had TI installed when you generated these biomes? If you did, try looking more closely, you might have missed the decorations.

**Comment by SirChamomile** [comment]
Issue seems to be resolved here https://github.com/team-abnormals/autumnity/issues/63.
