### ISSUE TITLE
[1.18.2] Crash on world creation or exploring new chunks from old worlds(pre 2.0)

### ISSUE THREAD

**Issue by dr3ams** [Azmalent/terra-incognita#75]
**java.lang.IllegalStateException: Feature order cycle found**

Tried exploring new chunks in old world(from 2.0 BETA) got crash mentioning Blueprint library:
https://pastebin.com/xgJy8pkE

deleted Blueprint library and all related mods to it and then tried to generate new world:
https://pastebin.com/jHVrapUf

terraincognita-1.18.2-2.0.1
cuneiform-1.18.2-1.3.4
TerraBlender-forge-1.18.2-1.2.0.126

Is 2.0 update compatible with old worlds, created in BETA?

**Comment by Azmalent** [comment]
The 2.0 release _should_ be fully compatible, except for the fact that sedge got renamed back to swamp reeds, so it will disappear from existing worlds. I didn't bother with remapping IDs because reeds have new blockstates, so they would break in old worlds regardless.

This error is really weird, after a quick check I don't see anything that could be causing it. Could you please install [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) and post the new logs?

**Comment by dr3ams** [comment]
Weird, I thought I was going insane when it suddenly fixed itself but that was because I added Cyanide. 

It crashes without Cyanide and works with Cyanide.

Anyway, here's the latest.log of world creation:
https://gist.github.com/dr3ams/2ffa5e09db2b7e0ba86e7164185f58fd

**Comment by Azmalent** [comment]
This is strange. Feature order cycles are hard to debug because they are random and inconsistent. 

Basically, it's what happens when biome A generates flowers first and then grass (for example), while biome B does it in reverse order. So when they are next to each other and the game generates features on the biome border, it doesn't know what to generate first, so it crashes.
